//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ats.Web.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_vi {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_vi() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ats.Web.Resources.Resource.vi", typeof(Resource_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        public static string Actitvities {
            get {
                return ResourceManager.GetString("Actitvities", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        public static string AddActivitys {
            get {
                return ResourceManager.GetString("AddActivitys", resourceCulture);
            }
        }
        
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        public static string AddDepartmentUser {
            get {
                return ResourceManager.GetString("AddDepartmentUser", resourceCulture);
            }
        }
        
        public static string AddLeaveType {
            get {
                return ResourceManager.GetString("AddLeaveType", resourceCulture);
            }
        }
        
        public static string AddLeaveTypess {
            get {
                return ResourceManager.GetString("AddLeaveTypess", resourceCulture);
            }
        }
        
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        public static string AddProjectRole {
            get {
                return ResourceManager.GetString("AddProjectRole", resourceCulture);
            }
        }
        
        public static string AddProjectUser {
            get {
                return ResourceManager.GetString("AddProjectUser", resourceCulture);
            }
        }
        
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        public static string AddRoleGroup {
            get {
                return ResourceManager.GetString("AddRoleGroup", resourceCulture);
            }
        }
        
        public static string AddRoless {
            get {
                return ResourceManager.GetString("AddRoless", resourceCulture);
            }
        }
        
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        public static string AddTemplate {
            get {
                return ResourceManager.GetString("AddTemplate", resourceCulture);
            }
        }
        
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        public static string AddUserLeave {
            get {
                return ResourceManager.GetString("AddUserLeave", resourceCulture);
            }
        }
        
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        public static string AdvertisingPreferences {
            get {
                return ResourceManager.GetString("AdvertisingPreferences", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        public static string AlreadyHadAccount {
            get {
                return ResourceManager.GetString("AlreadyHadAccount", resourceCulture);
            }
        }
        
        public static string Approvals {
            get {
                return ResourceManager.GetString("Approvals", resourceCulture);
            }
        }
        
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        public static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        public static string CantSubmitThroughYear {
            get {
                return ResourceManager.GetString("CantSubmitThroughYear", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string ChangePW {
            get {
                return ResourceManager.GetString("ChangePW", resourceCulture);
            }
        }
        
        public static string ChangePWForm {
            get {
                return ResourceManager.GetString("ChangePWForm", resourceCulture);
            }
        }
        
        public static string ChangePwSuccessfully {
            get {
                return ResourceManager.GetString("ChangePwSuccessfully", resourceCulture);
            }
        }
        
        public static string Chargeable {
            get {
                return ResourceManager.GetString("Chargeable", resourceCulture);
            }
        }
        
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        public static string ConfirmNewPW {
            get {
                return ResourceManager.GetString("ConfirmNewPW", resourceCulture);
            }
        }
        
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        public static string Copyright1 {
            get {
                return ResourceManager.GetString("Copyright1", resourceCulture);
            }
        }
        
        public static string CreatePW {
            get {
                return ResourceManager.GetString("CreatePW", resourceCulture);
            }
        }
        
        public static string CurPW {
            get {
                return ResourceManager.GetString("CurPW", resourceCulture);
            }
        }
        
        public static string Currentdate {
            get {
                return ResourceManager.GetString("Currentdate", resourceCulture);
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        public static string DaysAvai {
            get {
                return ResourceManager.GetString("DaysAvai", resourceCulture);
            }
        }
        
        public static string Dayss {
            get {
                return ResourceManager.GetString("Dayss", resourceCulture);
            }
        }
        
        public static string DayYear {
            get {
                return ResourceManager.GetString("DayYear", resourceCulture);
            }
        }
        
        public static string DelConfirm {
            get {
                return ResourceManager.GetString("DelConfirm", resourceCulture);
            }
        }
        
        public static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        public static string DepartmentSumaryReport {
            get {
                return ResourceManager.GetString("DepartmentSumaryReport", resourceCulture);
            }
        }
        
        public static string DepartmentUser {
            get {
                return ResourceManager.GetString("DepartmentUser", resourceCulture);
            }
        }
        
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        public static string Disapprove {
            get {
                return ResourceManager.GetString("Disapprove", resourceCulture);
            }
        }
        
        public static string Disapproved {
            get {
                return ResourceManager.GetString("Disapproved", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string EditActivity {
            get {
                return ResourceManager.GetString("EditActivity", resourceCulture);
            }
        }
        
        public static string EditDepartment {
            get {
                return ResourceManager.GetString("EditDepartment", resourceCulture);
            }
        }
        
        public static string EditDepartmentUser {
            get {
                return ResourceManager.GetString("EditDepartmentUser", resourceCulture);
            }
        }
        
        public static string EditLeaveType {
            get {
                return ResourceManager.GetString("EditLeaveType", resourceCulture);
            }
        }
        
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        public static string EditRoleGroup {
            get {
                return ResourceManager.GetString("EditRoleGroup", resourceCulture);
            }
        }
        
        public static string EditRoless {
            get {
                return ResourceManager.GetString("EditRoless", resourceCulture);
            }
        }
        
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        public static string EditUserLeave {
            get {
                return ResourceManager.GetString("EditUserLeave", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        public static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        public static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        public static string EndDateMustGreaterFromDate {
            get {
                return ResourceManager.GetString("EndDateMustGreaterFromDate", resourceCulture);
            }
        }
        
        public static string EndTimeMustGreaterStart {
            get {
                return ResourceManager.GetString("EndTimeMustGreaterStart", resourceCulture);
            }
        }
        
        public static string ErrorConfirmPW {
            get {
                return ResourceManager.GetString("ErrorConfirmPW", resourceCulture);
            }
        }
        
        public static string ExLoginCont1 {
            get {
                return ResourceManager.GetString("ExLoginCont1", resourceCulture);
            }
        }
        
        public static string ExLoginCont2 {
            get {
                return ResourceManager.GetString("ExLoginCont2", resourceCulture);
            }
        }
        
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        public static string FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("FailedToVerifyPhone", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        public static string Grey {
            get {
                return ResourceManager.GetString("Grey", resourceCulture);
            }
        }
        
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        public static string HoursAvai {
            get {
                return ResourceManager.GetString("HoursAvai", resourceCulture);
            }
        }
        
        public static string HoursMustGreaterThanZero {
            get {
                return ResourceManager.GetString("HoursMustGreaterThanZero", resourceCulture);
            }
        }
        
        public static string HoursMustGreaterZeroTimeIncorrect {
            get {
                return ResourceManager.GetString("HoursMustGreaterZeroTimeIncorrect", resourceCulture);
            }
        }
        
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        public static string IncorrectPw {
            get {
                return ResourceManager.GetString("IncorrectPw", resourceCulture);
            }
        }
        
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        public static string LeaveApprovals {
            get {
                return ResourceManager.GetString("LeaveApprovals", resourceCulture);
            }
        }
        
        public static string LeaveForm {
            get {
                return ResourceManager.GetString("LeaveForm", resourceCulture);
            }
        }
        
        public static string LeaveReport {
            get {
                return ResourceManager.GetString("LeaveReport", resourceCulture);
            }
        }
        
        public static string LeaveReportServices {
            get {
                return ResourceManager.GetString("LeaveReportServices", resourceCulture);
            }
        }
        
        public static string Leaves {
            get {
                return ResourceManager.GetString("Leaves", resourceCulture);
            }
        }
        
        public static string LeaveSummary {
            get {
                return ResourceManager.GetString("LeaveSummary", resourceCulture);
            }
        }
        
        public static string LeaveSummaryUser {
            get {
                return ResourceManager.GetString("LeaveSummaryUser", resourceCulture);
            }
        }
        
        public static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        public static string LeaveTypes {
            get {
                return ResourceManager.GetString("LeaveTypes", resourceCulture);
            }
        }
        
        public static string LeaveTypess {
            get {
                return ResourceManager.GetString("LeaveTypess", resourceCulture);
            }
        }
        
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        public static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Loginss {
            get {
                return ResourceManager.GetString("Loginss", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        public static string ManageExLogin {
            get {
                return ResourceManager.GetString("ManageExLogin", resourceCulture);
            }
        }
        
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        public static string ManageTitle {
            get {
                return ResourceManager.GetString("ManageTitle", resourceCulture);
            }
        }
        
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        public static string MonthlyLeaves {
            get {
                return ResourceManager.GetString("MonthlyLeaves", resourceCulture);
            }
        }
        
        public static string MyApprovals {
            get {
                return ResourceManager.GetString("MyApprovals", resourceCulture);
            }
        }
        
        public static string MyDepartments {
            get {
                return ResourceManager.GetString("MyDepartments", resourceCulture);
            }
        }
        
        public static string MyLeave {
            get {
                return ResourceManager.GetString("MyLeave", resourceCulture);
            }
        }
        
        public static string MyProject {
            get {
                return ResourceManager.GetString("MyProject", resourceCulture);
            }
        }
        
        public static string MyTimeSheet {
            get {
                return ResourceManager.GetString("MyTimeSheet", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string NewActivity {
            get {
                return ResourceManager.GetString("NewActivity", resourceCulture);
            }
        }
        
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        public static string NewDepartment {
            get {
                return ResourceManager.GetString("NewDepartment", resourceCulture);
            }
        }
        
        public static string NewLeave {
            get {
                return ResourceManager.GetString("NewLeave", resourceCulture);
            }
        }
        
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        public static string NewPW {
            get {
                return ResourceManager.GetString("NewPW", resourceCulture);
            }
        }
        
        public static string NewRole {
            get {
                return ResourceManager.GetString("NewRole", resourceCulture);
            }
        }
        
        public static string NewRoleGroup {
            get {
                return ResourceManager.GetString("NewRoleGroup", resourceCulture);
            }
        }
        
        public static string NewTemplate {
            get {
                return ResourceManager.GetString("NewTemplate", resourceCulture);
            }
        }
        
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        public static string OverAvailableTime {
            get {
                return ResourceManager.GetString("OverAvailableTime", resourceCulture);
            }
        }
        
        public static string Overflow {
            get {
                return ResourceManager.GetString("Overflow", resourceCulture);
            }
        }
        
        public static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        public static string PaidLeave {
            get {
                return ResourceManager.GetString("PaidLeave", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        public static string Projectss {
            get {
                return ResourceManager.GetString("Projectss", resourceCulture);
            }
        }
        
        public static string ProjectsTemplate {
            get {
                return ResourceManager.GetString("ProjectsTemplate", resourceCulture);
            }
        }
        
        public static string ProjectSumaryReport {
            get {
                return ResourceManager.GetString("ProjectSumaryReport", resourceCulture);
            }
        }
        
        public static string ProjectTemplate {
            get {
                return ResourceManager.GetString("ProjectTemplate", resourceCulture);
            }
        }
        
        public static string ProjectUser {
            get {
                return ResourceManager.GetString("ProjectUser", resourceCulture);
            }
        }
        
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        public static string ResetPW {
            get {
                return ResourceManager.GetString("ResetPW", resourceCulture);
            }
        }
        
        public static string ResignationDate {
            get {
                return ResourceManager.GetString("ResignationDate", resourceCulture);
            }
        }
        
        public static string ResourcePage {
            get {
                return ResourceManager.GetString("ResourcePage", resourceCulture);
            }
        }
        
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string RoleGroups {
            get {
                return ResourceManager.GetString("RoleGroups", resourceCulture);
            }
        }
        
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        public static string Submitting {
            get {
                return ResourceManager.GetString("Submitting", resourceCulture);
            }
        }
        
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        public static string ThisArticle {
            get {
                return ResourceManager.GetString("ThisArticle", resourceCulture);
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string TimeLog {
            get {
                return ResourceManager.GetString("TimeLog", resourceCulture);
            }
        }
        
        public static string TimeLogs {
            get {
                return ResourceManager.GetString("TimeLogs", resourceCulture);
            }
        }
        
        public static string Timesheet {
            get {
                return ResourceManager.GetString("Timesheet", resourceCulture);
            }
        }
        
        public static string TimesheetApprovals {
            get {
                return ResourceManager.GetString("TimesheetApprovals", resourceCulture);
            }
        }
        
        public static string TimesheetReport {
            get {
                return ResourceManager.GetString("TimesheetReport", resourceCulture);
            }
        }
        
        public static string TimesheetReportServices {
            get {
                return ResourceManager.GetString("TimesheetReportServices", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string TotalAvailableTime {
            get {
                return ResourceManager.GetString("TotalAvailableTime", resourceCulture);
            }
        }
        
        public static string TotalRequestedTime {
            get {
                return ResourceManager.GetString("TotalRequestedTime", resourceCulture);
            }
        }
        
        public static string TwoFactor {
            get {
                return ResourceManager.GetString("TwoFactor", resourceCulture);
            }
        }
        
        public static string TwoFactorCont1 {
            get {
                return ResourceManager.GetString("TwoFactorCont1", resourceCulture);
            }
        }
        
        public static string TwoFactorCont2 {
            get {
                return ResourceManager.GetString("TwoFactorCont2", resourceCulture);
            }
        }
        
        public static string TypeToSearch {
            get {
                return ResourceManager.GetString("TypeToSearch", resourceCulture);
            }
        }
        
        public static string UserCodeAlreadyExists {
            get {
                return ResourceManager.GetString("UserCodeAlreadyExists", resourceCulture);
            }
        }
        
        public static string UserDetail {
            get {
                return ResourceManager.GetString("UserDetail", resourceCulture);
            }
        }
        
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        public static string UserIsEmpty {
            get {
                return ResourceManager.GetString("UserIsEmpty", resourceCulture);
            }
        }
        
        public static string UserLeaveSetting {
            get {
                return ResourceManager.GetString("UserLeaveSetting", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        public static string UsernameOrPwIncorrect {
            get {
                return ResourceManager.GetString("UsernameOrPwIncorrect", resourceCulture);
            }
        }
        
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        public static string UserProject {
            get {
                return ResourceManager.GetString("UserProject", resourceCulture);
            }
        }
        
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        public static string UTS {
            get {
                return ResourceManager.GetString("UTS", resourceCulture);
            }
        }
        
        public static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        public static string WithdrawSuccessfully {
            get {
                return ResourceManager.GetString("WithdrawSuccessfully", resourceCulture);
            }
        }
        
        public static string YearlyLeaves {
            get {
                return ResourceManager.GetString("YearlyLeaves", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string YourSecurityCode {
            get {
                return ResourceManager.GetString("YourSecurityCode", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string CompanyEmployee {
            get {
                return ResourceManager.GetString("CompanyEmployee", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        public static string AdditionalEmail {
            get {
                return ResourceManager.GetString("AdditionalEmail", resourceCulture);
            }
        }
        
        public static string AdditionalPhone {
            get {
                return ResourceManager.GetString("AdditionalPhone", resourceCulture);
            }
        }
        
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        public static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        public static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        public static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        public static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        public static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        public static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        public static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        public static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        public static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        public static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        public static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        public static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        public static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        public static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        public static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        public static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        public static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        public static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        public static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        public static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        public static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        public static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        public static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        public static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        public static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        public static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        public static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        public static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        public static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        public static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        public static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        public static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        public static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        public static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        public static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        public static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        public static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        public static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        public static string PleaseAddLeaveType {
            get {
                return ResourceManager.GetString("PleaseAddLeaveType", resourceCulture);
            }
        }
        
        public static string PleaseSaveUser {
            get {
                return ResourceManager.GetString("PleaseSaveUser", resourceCulture);
            }
        }
        
        public static string asm_add_asset {
            get {
                return ResourceManager.GetString("asm-add-asset", resourceCulture);
            }
        }
        
        public static string asm_asset_management {
            get {
                return ResourceManager.GetString("asm-asset-management", resourceCulture);
            }
        }
        
        public static string asm_search {
            get {
                return ResourceManager.GetString("asm-search", resourceCulture);
            }
        }
        
        public static string asm_inventory {
            get {
                return ResourceManager.GetString("asm-inventory", resourceCulture);
            }
        }
        
        public static string AssetCategory {
            get {
                return ResourceManager.GetString("AssetCategory", resourceCulture);
            }
        }
        
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        public static string NewAssetCategory {
            get {
                return ResourceManager.GetString("NewAssetCategory", resourceCulture);
            }
        }
        
        public static string AssetCategoryParent {
            get {
                return ResourceManager.GetString("AssetCategoryParent", resourceCulture);
            }
        }
        
        public static string AddAssetCategory {
            get {
                return ResourceManager.GetString("AddAssetCategory", resourceCulture);
            }
        }
        
        public static string EditAssetCategory {
            get {
                return ResourceManager.GetString("EditAssetCategory", resourceCulture);
            }
        }
        
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        public static string PurposeDescription {
            get {
                return ResourceManager.GetString("PurposeDescription", resourceCulture);
            }
        }
        
        public static string EditInventory {
            get {
                return ResourceManager.GetString("EditInventory", resourceCulture);
            }
        }
        
        public static string NewInventory {
            get {
                return ResourceManager.GetString("NewInventory", resourceCulture);
            }
        }
        
        public static string AddInventory {
            get {
                return ResourceManager.GetString("AddInventory", resourceCulture);
            }
        }
        
        public static string LocationDescription {
            get {
                return ResourceManager.GetString("LocationDescription", resourceCulture);
            }
        }
        
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        public static string InventoryType {
            get {
                return ResourceManager.GetString("InventoryType", resourceCulture);
            }
        }
        
        public static string LinkedId {
            get {
                return ResourceManager.GetString("LinkedId", resourceCulture);
            }
        }
        
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        public static string AddVendor {
            get {
                return ResourceManager.GetString("AddVendor", resourceCulture);
            }
        }
        
        public static string EditVendor {
            get {
                return ResourceManager.GetString("EditVendor", resourceCulture);
            }
        }
        
        public static string NewVendor {
            get {
                return ResourceManager.GetString("NewVendor", resourceCulture);
            }
        }
        
        public static string BuyDate {
            get {
                return ResourceManager.GetString("BuyDate", resourceCulture);
            }
        }
        
        public static string BuyPrice {
            get {
                return ResourceManager.GetString("BuyPrice", resourceCulture);
            }
        }
        
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        public static string Warranty {
            get {
                return ResourceManager.GetString("Warranty", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string WarrantyDueDate {
            get {
                return ResourceManager.GetString("WarrantyDueDate", resourceCulture);
            }
        }
        
        public static string asm_edit_asset {
            get {
                return ResourceManager.GetString("asm_edit_asset", resourceCulture);
            }
        }
        
        public static string FileAttachment {
            get {
                return ResourceManager.GetString("FileAttachment", resourceCulture);
            }
        }
        
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string ApproveUser {
            get {
                return ResourceManager.GetString("ApproveUser", resourceCulture);
            }
        }
        
        public static string Buyer {
            get {
                return ResourceManager.GetString("Buyer", resourceCulture);
            }
        }
        
        public static string OwnerUser {
            get {
                return ResourceManager.GetString("OwnerUser", resourceCulture);
            }
        }
        
        public static string RequestUser {
            get {
                return ResourceManager.GetString("RequestUser", resourceCulture);
            }
        }
        
        public static string Return_ApprovalUser {
            get {
                return ResourceManager.GetString("Return_ApprovalUser", resourceCulture);
            }
        }
        
        public static string Return_PurposeDescription {
            get {
                return ResourceManager.GetString("Return_PurposeDescription", resourceCulture);
            }
        }
        
        public static string Return_RequestUser {
            get {
                return ResourceManager.GetString("Return_RequestUser", resourceCulture);
            }
        }
        
        public static string TransferInventory {
            get {
                return ResourceManager.GetString("TransferInventory", resourceCulture);
            }
        }
        
        public static string Usage_ApprovalUser {
            get {
                return ResourceManager.GetString("Usage_ApprovalUser", resourceCulture);
            }
        }
        
        public static string Usage_PurposeDescription {
            get {
                return ResourceManager.GetString("Usage_PurposeDescription", resourceCulture);
            }
        }
        
        public static string Usage_RequestUser {
            get {
                return ResourceManager.GetString("Usage_RequestUser", resourceCulture);
            }
        }
        
        public static string TransferItem {
            get {
                return ResourceManager.GetString("TransferItem", resourceCulture);
            }
        }
        
        public static string WarrantyFromDate {
            get {
                return ResourceManager.GetString("WarrantyFromDate", resourceCulture);
            }
        }
        
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        public static string DateRequest {
            get {
                return ResourceManager.GetString("DateRequest", resourceCulture);
            }
        }
        
        public static string ApprovalDate {
            get {
                return ResourceManager.GetString("ApprovalDate", resourceCulture);
            }
        }
        
        public static string ApprovalDateIsInvalid {
            get {
                return ResourceManager.GetString("ApprovalDateIsInvalid", resourceCulture);
            }
        }
        
        public static string UserApprovalIsInValid {
            get {
                return ResourceManager.GetString("UserApprovalIsInValid", resourceCulture);
            }
        }
        
        public static string AssetApproval {
            get {
                return ResourceManager.GetString("AssetApproval", resourceCulture);
            }
        }
        
        public static string DateApproval {
            get {
                return ResourceManager.GetString("DateApproval", resourceCulture);
            }
        }
        
        public static string ApproveType {
            get {
                return ResourceManager.GetString("ApproveType", resourceCulture);
            }
        }
        
        public static string SaveAndNew {
            get {
                return ResourceManager.GetString("SaveAndNew", resourceCulture);
            }
        }
        
        public static string ApprovalDescription {
            get {
                return ResourceManager.GetString("ApprovalDescription", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ErrorTransferInventory {
            get {
                return ResourceManager.GetString("ErrorTransferInventory", resourceCulture);
            }
        }
        
        public static string ErrorTransferItem {
            get {
                return ResourceManager.GetString("ErrorTransferItem", resourceCulture);
            }
        }
        
        public static string CannotDeleteInventoryItem {
            get {
                return ResourceManager.GetString("CannotDeleteInventoryItem", resourceCulture);
            }
        }
        
        public static string CannotDeleteItemAssignment {
            get {
                return ResourceManager.GetString("CannotDeleteItemAssignment", resourceCulture);
            }
        }
        
        public static string EditProjectUser {
            get {
                return ResourceManager.GetString("EditProjectUser", resourceCulture);
            }
        }
        
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        public static string StartDateProUser {
            get {
                return ResourceManager.GetString("StartDateProUser", resourceCulture);
            }
        }
        
        public static string AddBranch {
            get {
                return ResourceManager.GetString("AddBranch", resourceCulture);
            }
        }
        
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        public static string BranchOffice {
            get {
                return ResourceManager.GetString("BranchOffice", resourceCulture);
            }
        }
        
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string EditBranch {
            get {
                return ResourceManager.GetString("EditBranch", resourceCulture);
            }
        }
        
        public static string EditCompany {
            get {
                return ResourceManager.GetString("EditCompany", resourceCulture);
            }
        }
        
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        public static string FoundedDate {
            get {
                return ResourceManager.GetString("FoundedDate", resourceCulture);
            }
        }
        
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
    }
}
