using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace Ats.Domain
{
    public enum VN_PROVINCE
    {
        [Display(Name = "Hà Nội")]
        HA_NOI = 1,
        [Display(Name = "Hà Giang")]
        HA_GIANG = 2,
        [Display(Name = "Cao Bằng")]
        CAO_BANG = 4,
        [Display(Name = "Bắc Kạn")]
        BAC_KAN = 6,
        [Display(Name = "Tuyên Quang")]
        TUYEN_QUANG = 8,
        [Display(Name = "Lào Cai")]
        LAO_CAI = 10,
        [Display(Name = "Điện Biên")]
        DIEN_BIEN = 11,
        [Display(Name = "Lai Châu")]
        LAI_CHAU = 12,
        [Display(Name = "Sơn La")]
        SON_LA = 14,
        [Display(Name = "Yên Bái")]
        YEN_BAI = 15,
        [Display(Name = "Hòa Bình")]
        HOA_BINH = 17,
        [Display(Name = "Thái Nguyên")]
        THAI_NGUYEN = 19,
        [Display(Name = "Lạng Sơn")]
        LANG_SON = 20,
        [Display(Name = "Quảng Ninh")]
        QUANG_NINH = 22,
        [Display(Name = "Bắc Giang")]
        BAC_GIANG = 24,
        [Display(Name = "Phú Thọ")]
        PHU_THO = 25,
        [Display(Name = "Vĩnh Phúc")]
        VINH_PHUC = 26,
        [Display(Name = "Bắc Ninh")]
        BAC_NINH = 27,
        [Display(Name = "Hải Dương")]
        HAI_DUONG = 30,
        [Display(Name = "Hải Phòng")]
        HAI_PHONG = 31,
        [Display(Name = "Hưng Yên")]
        HUNG_YEN = 33,
        [Display(Name = "Thái Bình")]
        THAI_BINH = 34,
        [Display(Name = "Hà Nam")]
        HA_NAM = 35,
        [Display(Name = "Nam Định")]
        NAM_DINH = 36,
        [Display(Name = "Ninh Bình")]
        NINH_BINH = 37,
        [Display(Name = "Thanh Hóa")]
        THANH_HOA = 38,
        [Display(Name = "Nghệ An")]
        NGHE_AN = 40,
        [Display(Name = "Hà Tĩnh")]
        HA_TINH = 42,
        [Display(Name = "Quảng Bình")]
        QUANG_BINH = 44,
        [Display(Name = "Quảng Trị")]
        QUANG_TRI = 45,
        [Display(Name = "Thừa Thiên Huế")]
        THUA_THIEN_HUE = 46,
        [Display(Name = "Đà Nẵng")]
        DA_NANG = 48,
        [Display(Name = "Quảng Nam")]
        QUANG_NAM = 49,
        [Display(Name = "Quảng Ngãi")]
        QUANG_NGAI = 51,
        [Display(Name = "Bình Định")]
        BINH_DINH = 52,
        [Display(Name = "Phú Yên")]
        PHU_YEN = 54,
        [Display(Name = "Khánh Hòa")]
        KHANH_HOA = 56,
        [Display(Name = "Ninh Thuận")]
        NINH_THUAN = 58,
        [Display(Name = "Bình Thuận")]
        BINH_THUAN = 60,
        [Display(Name = "Kon Tum")]
        KON_TUM = 62, 
        [Display(Name = "Gia Lai")]
        GIA_LAI = 64,
        [Display(Name = "Đắk Lắk")]
        DAK_LAK = 66,
        [Display(Name = "Đắk Nông")]
        DAK_NONG = 67,
        [Display(Name = "Lâm Đồng")]
        LAM_DONG = 68,
        [Display(Name = "Bình Phước")]
        BINH_PHUOC = 70,
        [Display(Name = "Tây Ninh")]
        TAY_NINH = 72,
        [Display(Name = "Bình Dương")]
        BINH_DUONG = 74,
        [Display(Name = "Đồng Nai")]
        DONG_NAI = 75,
        [Display(Name = "Bà Rịa - Vũng Tàu")]
        BA_RIA_VUNG_TAU = 77,
        [Display(Name = "Hồ Chí Minh")]
        HO_CHI_MINH = 79,
        [Display(Name = "Long An")]
        LONG_AN = 80,
        [Display(Name = "Tiền Giang")]
        TIEN_GIANG = 82,
        [Display(Name = "Bến Tre")]
        BEN_TRE = 83,
        [Display(Name = "Trà Vinh")]
        TRA_VINH = 84,
        [Display(Name = "Vĩnh Long")]
        VINH_LONG = 86,
        [Display(Name = "Đồng Tháp")]
        DONG_THAP = 87,
        [Display(Name = "An Giang")]
        AN_GIANG = 89,
        [Display(Name = "Kiên Giang")]
        KIEN_GIANG = 91,
        [Display(Name = "Cần Thơ")]
        CAN_THO = 92,
        [Display(Name = "Hậu Giang")]
        HAU_GIANG = 93,
        [Display(Name = "Sóc Trăng")]
        SOC_TRANG = 94,
        [Display(Name = "Bạc Liêu")]
        BAC_LIEU = 95,
        [Display(Name = "Cà Mau")]
        CA_MAU = 96,        
    }
}
